package com.moai.endpoints.models;
// Generated 5/08/2018 04:10:19 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * CategoryProject generated by hbm2java
 */
public class CategoryProject  implements java.io.Serializable {


     private int idCat;
     private String nameCategory;
     private List<Project> projects = new ArrayList<>(0);

    public CategoryProject() {
    }

	
    public CategoryProject(int idCat, String nameCategory) {
        this.idCat = idCat;
        this.nameCategory = nameCategory;
    }

    public int getIdCat() {
        return idCat;
    }

    public void setIdCat(int idCat) {
        this.idCat = idCat;
    }

    public String getNameCategory() {
        return nameCategory;
    }

    public void setNameCategory(String nameCategory) {
        this.nameCategory = nameCategory;
    }

    public List<Project> getProjects() {
        return projects;
    }

    public void setProjects(List<Project> projects) {
        this.projects = projects;
    }
}


