package com.moai.endpoints.models;
// Generated 5/08/2018 04:10:19 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DateProject generated by hbm2java
 */
public class DateProject  implements java.io.Serializable {


     private int idDate;
     private Project project;
     private String nameDate;
     private Date valueDate;

    public DateProject() {
    }

    public DateProject(int idDate, Project project, String nameDate, Date valueDate) {
       this.idDate = idDate;
       this.project = project;
       this.nameDate = nameDate;
       this.valueDate = valueDate;
    }
   
    public int getIdDate() {
        return this.idDate;
    }
    
    public void setIdDate(int idDate) {
        this.idDate = idDate;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public String getNameDate() {
        return this.nameDate;
    }
    
    public void setNameDate(String nameDate) {
        this.nameDate = nameDate;
    }
    public Date getValueDate() {
        return this.valueDate;
    }
    
    public void setValueDate(Date valueDate) {
        this.valueDate = valueDate;
    }




}


