package com.moai.endpoints.models;
// Generated 5/08/2018 04:10:19 AM by Hibernate Tools 4.3.1



/**
 * Inversion generated by hbm2java
 */
public class Inversion  implements java.io.Serializable {


     private int idInversion;
     private ResourceNeedCapacity resourceNeedCapacity;
     private User user;
     private int status;

    public Inversion() {
    }

    public Inversion(int idInversion, ResourceNeedCapacity resourceNeedCapacity, User user, int status) {
       this.idInversion = idInversion;
       this.resourceNeedCapacity = resourceNeedCapacity;
       this.user = user;
       this.status = status;
    }
   
    public int getIdInversion() {
        return this.idInversion;
    }
    
    public void setIdInversion(int idInversion) {
        this.idInversion = idInversion;
    }
    public ResourceNeedCapacity getResourceNeedCapacity() {
        return this.resourceNeedCapacity;
    }
    
    public void setResourceNeedCapacity(ResourceNeedCapacity resourceNeedCapacity) {
        this.resourceNeedCapacity = resourceNeedCapacity;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


