package com.moai.endpoints.models;
// Generated 5/08/2018 04:10:19 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private LocationId id;
     private Location location;
     private String nameLocation;
     private List<Project> projects = new ArrayList<>(0);
     private List<Location> locations = new ArrayList<>(0);

    public Location() {
    }

	
    public Location(LocationId id, String nameLocation) {
        this.id = id;
        this.nameLocation = nameLocation;
    }

    public LocationId getId() {
        return id;
    }

    public void setId(LocationId id) {
        this.id = id;
    }

    public Location getLocation() {
        return location;
    }

    public void setLocation(Location location) {
        this.location = location;
    }

    public String getNameLocation() {
        return nameLocation;
    }

    public void setNameLocation(String nameLocation) {
        this.nameLocation = nameLocation;
    }

    public List<Project> getProjects() {
        return projects;
    }

    public void setProjects(List<Project> projects) {
        this.projects = projects;
    }

    public List<Location> getLocations() {
        return locations;
    }

    public void setLocations(List<Location> locations) {
        this.locations = locations;
    }
}


