package com.moai.endpoints.models;
// Generated 5/08/2018 04:10:19 AM by Hibernate Tools 4.3.1



/**
 * LocationId generated by hbm2java
 */
public class LocationId  implements java.io.Serializable {


     private String codLocation;
     private String typeLocation;

    public LocationId() {
    }

    public LocationId(String codLocation, String typeLocation) {
       this.codLocation = codLocation;
       this.typeLocation = typeLocation;
    }
   
    public String getCodLocation() {
        return this.codLocation;
    }
    
    public void setCodLocation(String codLocation) {
        this.codLocation = codLocation;
    }
    public String getTypeLocation() {
        return this.typeLocation;
    }
    
    public void setTypeLocation(String typeLocation) {
        this.typeLocation = typeLocation;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LocationId) ) return false;
		 LocationId castOther = ( LocationId ) other; 
         
		 return ( (this.getCodLocation()==castOther.getCodLocation()) || ( this.getCodLocation()!=null && castOther.getCodLocation()!=null && this.getCodLocation().equals(castOther.getCodLocation()) ) )
 && ( (this.getTypeLocation()==castOther.getTypeLocation()) || ( this.getTypeLocation()!=null && castOther.getTypeLocation()!=null && this.getTypeLocation().equals(castOther.getTypeLocation()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodLocation() == null ? 0 : this.getCodLocation().hashCode() );
         result = 37 * result + ( getTypeLocation() == null ? 0 : this.getTypeLocation().hashCode() );
         return result;
   }   


}


