package com.moai.endpoints.models;
// Generated 5/08/2018 04:10:19 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project  {


     private int idProject;
     private CategoryProject categoryProject;
     private Location location;
     private String nameProject;
     private String descriptionProject;
     private String objective;
     private String scope;
     private List<ResourceNeedCapacity> resourceNeedCapacities = new ArrayList<>(0);
     private List<DateProject> dateProjects = new ArrayList<>(0);
     private List<Risk> risks = new ArrayList<>(0);

    public Project() {
    }

    public int getIdProject() {
        return idProject;
    }

    public void setIdProject(int idProject) {
        this.idProject = idProject;
    }

    public CategoryProject getCategoryProject() {
        return categoryProject;
    }

    public void setCategoryProject(CategoryProject categoryProject) {
        this.categoryProject = categoryProject;
    }

    public Location getLocation() {
        return location;
    }

    public void setLocation(Location location) {
        this.location = location;
    }

    public String getNameProject() {
        return nameProject;
    }

    public void setNameProject(String nameProject) {
        this.nameProject = nameProject;
    }

    public String getDescriptionProject() {
        return descriptionProject;
    }

    public void setDescriptionProject(String descriptionProject) {
        this.descriptionProject = descriptionProject;
    }

    public String getObjective() {
        return objective;
    }

    public void setObjective(String objective) {
        this.objective = objective;
    }

    public String getScope() {
        return scope;
    }

    public void setScope(String scope) {
        this.scope = scope;
    }

    public List<ResourceNeedCapacity> getResourceNeedCapacities() {
        return resourceNeedCapacities;
    }

    public void setResourceNeedCapacities(List<ResourceNeedCapacity> resourceNeedCapacities) {
        this.resourceNeedCapacities = resourceNeedCapacities;
    }

    public List<DateProject> getDateProjects() {
        return dateProjects;
    }

    public void setDateProjects(List<DateProject> dateProjects) {
        this.dateProjects = dateProjects;
    }

    public List<Risk> getRisks() {
        return risks;
    }

    public void setRisks(List<Risk> risks) {
        this.risks = risks;
    }
}


