package com.moai.endpoints.models;
// Generated 5/08/2018 04:10:19 AM by Hibernate Tools 4.3.1



/**
 * Property generated by hbm2java
 */
public class Property  implements java.io.Serializable {


     private int idProperty;
     private MeasureUnit measureUnit;
     private ResourceNeedCapacity resourceNeedCapacity;
     private String nameProperty;
     private double value;

    public Property() {
    }

    public Property(int idProperty, MeasureUnit measureUnit, ResourceNeedCapacity resourceNeedCapacity, String nameProperty, double value) {
       this.idProperty = idProperty;
       this.measureUnit = measureUnit;
       this.resourceNeedCapacity = resourceNeedCapacity;
       this.nameProperty = nameProperty;
       this.value = value;
    }
   
    public int getIdProperty() {
        return this.idProperty;
    }
    
    public void setIdProperty(int idProperty) {
        this.idProperty = idProperty;
    }
    public MeasureUnit getMeasureUnit() {
        return this.measureUnit;
    }
    
    public void setMeasureUnit(MeasureUnit measureUnit) {
        this.measureUnit = measureUnit;
    }
    public ResourceNeedCapacity getResourceNeedCapacity() {
        return this.resourceNeedCapacity;
    }
    
    public void setResourceNeedCapacity(ResourceNeedCapacity resourceNeedCapacity) {
        this.resourceNeedCapacity = resourceNeedCapacity;
    }
    public String getNameProperty() {
        return this.nameProperty;
    }
    
    public void setNameProperty(String nameProperty) {
        this.nameProperty = nameProperty;
    }
    public double getValue() {
        return this.value;
    }
    
    public void setValue(double value) {
        this.value = value;
    }




}


