package com.moai.endpoints.models;
// Generated 5/08/2018 04:10:19 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Resource generated by hbm2java
 */
public class Resource  implements java.io.Serializable {


     private int idResource;
     private String nameResource;
     private List<ResourceNeedCapacity> resourceNeedCapacities = new ArrayList<>(0);

    public Resource() {
    }

	
    public Resource(int idResource, String nameResource) {
        this.idResource = idResource;
        this.nameResource = nameResource;
    }

    public int getIdResource() {
        return idResource;
    }

    public void setIdResource(int idResource) {
        this.idResource = idResource;
    }

    public String getNameResource() {
        return nameResource;
    }

    public void setNameResource(String nameResource) {
        this.nameResource = nameResource;
    }

    public List<ResourceNeedCapacity> getResourceNeedCapacities() {
        return resourceNeedCapacities;
    }

    public void setResourceNeedCapacities(List<ResourceNeedCapacity> resourceNeedCapacities) {
        this.resourceNeedCapacities = resourceNeedCapacities;
    }
}


