package com.moai.endpoints.models;
// Generated 5/08/2018 04:10:19 AM by Hibernate Tools 4.3.1



/**
 * Risk generated by hbm2java
 */
public class Risk  implements java.io.Serializable {


     private int idRisk;
     private Project project;
     private String nameRisk;
     private String descriptionRisk;

    public Risk() {
    }

    public Risk(int idRisk, Project project, String nameRisk, String descriptionRisk) {
       this.idRisk = idRisk;
       this.project = project;
       this.nameRisk = nameRisk;
       this.descriptionRisk = descriptionRisk;
    }
   
    public int getIdRisk() {
        return this.idRisk;
    }
    
    public void setIdRisk(int idRisk) {
        this.idRisk = idRisk;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public String getNameRisk() {
        return this.nameRisk;
    }
    
    public void setNameRisk(String nameRisk) {
        this.nameRisk = nameRisk;
    }
    public String getDescriptionRisk() {
        return this.descriptionRisk;
    }
    
    public void setDescriptionRisk(String descriptionRisk) {
        this.descriptionRisk = descriptionRisk;
    }




}


